branches:
  - master
  - feature
build:
  commands:
    - "npm install -g grunt-cli bower"
    - "npm install"
    - "bower install --allow-root"
    - "grunt test"
    - "grunt build"
  image: "node:6"
  name: coinomia-frontend
cache:
  mount:
    - node_modules
    - .git
    - bower_components

deploy:
  rsync:
    commands:
      - "sudo service nginx restart"
    delete: true
    exclude:
      - ".DS_Store"
    host: "$$SSH_HOST"
    port: "$$SSH_PORT"
    recursive: true
    source: ./dist/
    target: /usr/share/nginx/html/
    user: "$$SSH_USER"
    when:
      branch: "master"

  commands:
    image: "jmccann/drone-commands"
    commands:
      - "cd tools && sh build-push-images.sh"
    when:
      branch: "feature"

notify:
  email:
    from: drone@docker.appfactory.in
    host: "$$EMAIL_HOST"
    password: "$$EMAIL_PASSWORD"
    port: "$$EMAIL_PORT"
    recipients:
      - "aqabiz@allies.co.in"
      - "mohd.raza@allies.co.in"
    username: $$EMAIL_USERNAME
