build:
  commands:
    - "pwd"
    - "npm install -g grunt-cli bower"
    - "npm install"
    - "bower install --allow-root"
    - "grunt test"
    - "grunt build"
  image: "node:6"
  name: coinomia-frontend

cache:
  mount:
    - node_modules
    - .git
    - bower_components
publish:
  docker:
    repo: docker.appfactory.in/coinomia-frontend
    tag: latest
    file: Dockerfile

  docker:
    repo: docker.appfactory.in/coinomia-frontend
    tag: stable
    file: Dockerfile
    when:
      branch: "master"

deploy:
  rsync:
    commands:
      - "sh deployments/deploy.sh"
      - "sudo service nginx restart"
    delete: false
    host: $$SSH_HOST
    port: $$SSH_PORT
    recursive: true
    source: dist/
    target: /home/$$SSH_USER/deplyoments/dist_$$DRONE_BUILD_NUMBER/
    user: $$SSH_USER
    when:
      branch: [master, deploy-test]

  ssh:
    host:
      - $$DOCKER_HOST_1
    user: $$DOCKER_SSH_USER
    port: 22
    sleep: 5
    commands:
      - "sh deploy-staging.sh latest"
  ssh:
    host:
      - $$DOCKER_HOST_1
    user: $$DOCKER_SSH_USER
    port: 22
    sleep: 5
    commands:
      - "sh deploy-staging.sh stable"
    when:
      branch: master

notify:
  email:
    from: "drone@allies.co.in"
    host: $$EMAIL_HOST
    password: $$EMAIL_PASSWORD
    port: $$EMAIL_PORT
    recipients:
      - "aqabiz@allies.co.in"
      - "mohd.raza@allies.co.in"
    username: $$EMAIL_USERNAME
    subject: >
      [{{ build.status }}]
      {{ repo.owner }}/{{ repo.name }}
      ({{ build.branch }} - {{ truncate build.commit 8 }})
    template: >
      https://git.io/vgvPz
