build:
  image: node:6
  cache:
    mount:
      - node_modules
      - .git
      - bower_components
  name: coinomia-frontend
  commands:
    - npm install -g grunt-cli bower
    - npm install
    - bower install --allow-root
    - grunt test
    - grunt build

  notify:
    #   email:
    #     host: $$EMAIL_HOST
    #     port: $$EMAIL_PORT
    #     username: $$EMAIL_USERNAME
    #     password: $$EMAIL_PASSWORD
    #     from: drone@gogs.io
    #     recipients:
    #       - u@gogs.io
    #     when:
    #       repo: gogits/gogs
    # deploy:
    # bash:
    #   script:
    #     - 'perl deploy.pl'
