build:
  commands:
    - "pwd"
    - "npm install -g grunt-cli bower"
    - "npm install"
    - "bower install --allow-root"
    - "grunt test"
    - "grunt build"
    - "[ -d $DRONE_DIR/deploy/.git ] && rm -rf $DRONE_DIR/deploy/.git"
  image: "node:6"
  name: coinomia-frontend
cache:
  mount:
    - node_modules
    - .git
    - bower_components
publish:
  docker:
    repo: docker.appfactory.in/coinomia-frontend
    tag: latest
    file: Dockerfile
    when:
      branch: "feature"

deploy:
  rsync:
    commands:
      - "sudo service nginx restart"
    delete: true
    exclude:
      - ".DS_Store"
    host: "$$SSH_HOST"
    port: "$$SSH_PORT"
    recursive: true
    source: ./dist/
    target: /usr/share/nginx/html/cd/
    user: "$$SSH_USER"
    when:
      branch: "deploy-test"

  commands:
    image: "jmccann/drone-commands"
    commands:
      - "pwd"
      - "echo $$SSH_HOST"
      - "cd $DRONE_DIR && sh $DRON_DIR/build-push-images.sh"

notify:
  email:
    from: drone@docker.appfactory.in
    host: "$$EMAIL_HOST"
    password: "$$EMAIL_PASSWORD"
    port: "$$EMAIL_PORT"
    recipients:
      - "aqabiz@allies.co.in"
      - "mohd.raza@allies.co.in"
    username: $$EMAIL_USERNAME
