build:
  commands:
    - "pwd"
    - "npm install -g grunt-cli bower"
    - "npm install"
    - "bower install --allow-root"
    - "grunt test"
    - "grunt build"
  image: "node:6"
  name: coinomia-frontend

cache:
  mount:
    - node_modules
    - .git
    - bower_components
publish:
  docker:
    repo: docker.appfactory.in/coinomia-frontend
    tag: latest
    file: Dockerfile
    when:
      branch: "feature"
  docker:
    repo: docker.appfactory.in/coinomia-frontend
    tag: stable
    file: Dockerfile
    when:
      branch: "master"

deploy:
  rsync:
    commands:
      - "sudo service nginx restart"
    delete: true
    exclude:
      - ".DS_Store"
    host: "$$SSH_HOST"
    port: "$$SSH_PORT"
    recursive: true
    source: ./dist/
    target: /usr/share/nginx/html/cd/
    user: "$$SSH_USER"
    when:
      branch: [master, deploy-test]
  ssh:
    host:
      - $$DOCKER_HOST_1
    user: $$DOCKER_SSH_USER
    port: 22
    sleep: 5
    commands:
      - sh deploy-staging-latest.sh
    when:
      branch: feature
  ssh:
    host:
      - $$DOCKER_HOST_1
    user: $$DOCKER_SSH_USER
    port: 22
    sleep: 5
    commands:
      - sh deploy-staging-stable.sh
    when:
      branch: master

notify:
  email:
    from: drone@docker.appfactory.in
    host: "$$EMAIL_HOST"
    password: "$$EMAIL_PASSWORD"
    port: "$$EMAIL_PORT"
    recipients:
      - "aqabiz@allies.co.in"
      - "mohd.raza@allies.co.in"
    username: $$EMAIL_USERNAME
