build:
  commands:
    - "npm install -g grunt-cli bower"
    - "npm install"
    - "bower install --allow-root"
    - "grunt test"
    - "grunt build"
  image: "node:6"
  name: coinomia-frontend

deploy:
  bash:
    script:
      - "cd tools && sh build-push-images.sh"
  # rsync:
  #   commands:
  #     - "sudo service nginx restart"
  #   delete: true
  #   exclude:
  #     - ".DS_Store"
  #   host: $$SSH_HOST
  #   port: $$SSH_PORT
  #   recursive: true
  #   source: ./dist/
  #   target: /usr/share/nginx/html/
  #   user: $$SSH_USER
  #   when:
  #     - master
# notify:
#   email:
#     from: drone@docker.appfactory.in
#     host: $$EMAIL_HOST
#     password: $$EMAIL_PASSWORD
#     port: $$EMAIL_PORT
#     recipients:
#       - aqabiz@allies.co.in
#       - mohd.raza@allies.co.in
#     username: $$EMAIL_USERNAME
#     when:
#       repo: coinomia/coinomia-frontend
