'use strict';

/**
 * @ngdoc directive
 * @name coinomiaFrontendApp.directive:miningPayout
 * @description
 * # miningPayout
 */
angular.module('coinomiaFrontendApp')
  .directive('miningPayout', function () {
    return {
      restrict: 'A',
      templateUrl: 'views/directiveTemplates/miningPayouts.html',
      scope: {
        poolOptions: "=",
        machineOptions: "=",
        rackOptions: "=",
        btcPoolValue: "=",
        btcMachineValue: "=",
        btcRackValue: "=",
        ethPoolValue: "=",
        ethMachineValue: "=",
        ethRackValue: "=",
        dashPoolValue: "=",
        dashMachineValue: "=",
        dashRackValue: "=",
        moneroPoolValue: "=",
        moneroMachineValue: "=",
        moneroRackValue: "=",
        ltcPoolValue: "=",
        ltcMachineValue: "=",
        ltcRackValue: "=",
        viaPoolValue: "=",
        viaMachineValue: "=",
        viaRackValue: "=",
        poolDetails: "=",
        contributorDetails: "=",
        rackDetails: "=",
        currentMining: "=",
        btcPoolContract: "=",
        btcContributorContract: "=",
        btcRackContract: "=",
        ethPoolContract: "=",
        ethContributorContract: "=",
        ethRackContract: "=",
        dashPoolContract: "=",
        dashContributorContract: "=",
        dashRackContract: "=",
        moneroPoolContract: "=",
        moneroContributorContract: "=",
        moneroRackContract: "=",
        ltcPoolContract: "=",
        ltcContributorContract: "=",
        ltcRackContract: "=",
        viaPoolContract: "=",
        viaContributorContract: "=",
        viaRackContract: "=",
        btcPoolPrice: "=",
        btcContributorPrice: "=",
        btcRackPrice: "=",
        ethPoolPrice: "=",
        ethContributorPrice: "=",
        ethRackPrice: "=",
        dashPoolPrice: "=",
        dashContributorPrice: "=",
        dashRackPrice: "=",
        moneroPoolPrice: "=",
        moneroContributorPrice: "=",
        moneroRackPrice: "=",
        ltcPoolPrice: "=",
        ltcContributorPrice: "=",
        ltcRackPrice: "=",
        viaPoolPrice: "=",
        viaContributorPrice: "=",
        viaRackPrice: "=",
        btcPoolClick: "&",
        btcMachineClick: "&",
        btcRackClick: "&",
        ethPoolClick: "&",
        ethMachineClick: "&",
        ethRackClick: "&",
        dashPoolClick: "&",
        dashMachineClick: "&",
        dashRackClick: "&",
        moneroPoolClick: "&",
        moneroMachineClick: "&",
        moneroRackClick: "&",
        ltcPoolClick: "&",
        ltcMachineClick: "&",
        ltcRackClick: "&",
        viaPoolClick: "&",
        viaMachineClick: "&",
        viaRackClick: "&",
        btcPoolCalc: "&",
        btcContributorCalc: "&",
        btcRackCalc: "&",
        ethPoolCalc: "&",
        ethContributorCalc: "&",
        ethRackCalc: "&",
        dashPoolCalc: "&",
        dashContributorCalc: "&",
        dashRackCalc: "&",
        moneroPoolCalc: "&",
        moneroContributorCalc: "&",
        moneroRackCalc: "&",
        ltcPoolCalc: "&",
        ltcContributorCalc: "&",
        ltcRackCalc: "&",
        viaPoolCalc: "&",
        viaContributorCalc: "&",
        viaRackCalc: "&",
        s3Url:"="
      }
    };
  });
