'use strict';

/**
 * @ngdoc directive
 * @name coinomiaFrontendApp.directive:miningPayout
 * @description
 * # miningPayout
 */
angular.module('coinomiaFrontendApp')
  .directive('miningPayout', function () {
    return {
      restrict: 'A',
      templateUrl: 'views/directiveTemplates/miningPayouts.html',
      scope: {
        poolOptions: "=",
        machineOptions: "=",
        rackOptions: "=",
        btcPoolValue: "=",
        btcMachineValue: "=",
        btcRackValue: "=",
        ethPoolValue: "=",
        ethMachineValue: "=",
        ethRackValue: "=",
        dashPoolValue: "=",
        dashMachineValue: "=",
        dashRackValue: "=",
        moneroPoolValue: "=",
        moneroMachineValue: "=",
        moneroRackValue: "=",
        litePoolValue: "=",
        liteMachineValue: "=",
        liteRackValue: "=",
        poolDetails: "=",
        contributorDetails: "=",
        rackDetails: "=",
        currentMining: "=",
        btcPoolContract: "=",
        btcContributorContract: "=",
        btcRackContract: "=",
        ethPoolContract: "=",
        ethContributorContract: "=",
        ethRackContract: "=",
        dashPoolContract: "=",
        dashContributorContract: "=",
        dashRackContract: "=",
        moneroPoolContract: "=",
        moneroContributorContract: "=",
        moneroRackContract: "=",
        litePoolContract: "=",
        liteContributorContract: "=",
        liteRackContract: "=",
        btcPoolPrice: "=",
        btcContributorPrice: "=",
        btcRackPrice: "=",
        ethPoolPrice: "=",
        ethContributorPrice: "=",
        ethRackPrice: "=",
        dashPoolPrice: "=",
        dashContributorPrice: "=",
        dashRackPrice: "=",
        moneroPoolPrice: "=",
        moneroContributorPrice: "=",
        moneroRackPrice: "=",
        litePoolPrice: "=",
        liteContributorPrice: "=",
        liteRackPrice: "=",
        btcPoolClick: "&",
        btcMachineClick: "&",
        btcRackClick: "&",
        ethPoolClick: "&",
        ethMachineClick: "&",
        ethRackClick: "&",
        dashPoolClick: "&",
        dashMachineClick: "&",
        dashRackClick: "&",
        moneroPoolClick: "&",
        moneroMachineClick: "&",
        moneroRackClick: "&",
        litePoolClick: "&",
        liteMachineClick: "&",
        liteRackClick: "&",
        btcPoolCalc: "&",
        btcContributorCalc: "&",
        btcRackCalc: "&",
        ethPoolCalc: "&",
        ethContributorCalc: "&",
        ethRackCalc: "&",
        dashPoolCalc: "&",
        dashContributorCalc: "&",
        dashRackCalc: "&",
        moneroPoolCalc: "&",
        moneroContributorCalc: "&",
        moneroRackCalc: "&",
        litePoolCalc: "&",
        liteContributorCalc: "&",
        liteRackCalc: "&",
        s3Url:"="
      }
    };
  });
